name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome to Klimate Repo. Thank you for opening an issue'
        pr-message: 'Welcome to Klimate Repo. Thank you for your contribution, the maintainer will soon review your changes.'
